use customer_behaviour;
select * from customer_shopping_behavior limit 20;

-- 1. What is the total revenue generated by male vs. female customers ?

SELECT 
    gender, 
    SUM(`Purchase Amount (USD)`) AS revenue
FROM customer_shopping_behavior
GROUP BY gender;

-- 2. which customers used a discount but still spent mpore than the average purchase amount /

SELECT `ï»¿Customer ID`, `Purchase Amount (USD)`
FROM customer_shopping_behavior
WHERE `Discount Applied` = 'yes'
  AND `Purchase Amount (USD)` >= (
      SELECT AVG(`Purchase Amount (USD)`)
      FROM customer_shopping_behavior
  );
  
  -- 3. Which are the top 5 products with the highest average review rating ? 
  
SELECT `Item Purchased`, 
       ROUND(AVG(CAST(`Review Rating` AS DECIMAL(5,2))), 2) AS `Average Review Rating`
FROM customer_shopping_behavior
GROUP BY `Item Purchased`
ORDER BY AVG(CAST(`Review Rating` AS DECIMAL(5,2))) DESC
LIMIT 5;

-- 4. compare the average purchase amounts between standard and express shipping ?
select `Shipping Type`,
ROUND(AVG(`Purchase Amount (USD)`), 2)
from customer_shopping_behavior
where `Shipping Type` in ('standard', 'Express')
group by `Shipping Type`;

-- 5. Do subscribed customers spend more?
-- compare average spend and total revenue between subscribers and non subscribers

SELECT `Subscription Status`,
       COUNT(`ï»¿Customer ID`) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC, avg_spend DESC;

-- 6. which is 5 products have the highest percentage of purchases with discounts applied /
select 'Item Purchased',
ROUND(SUM(CASE WHEN 'Discount Applied' = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100, 2) 
as discount_rate 
from customer_shopping_behavior
group by 'Item Purchased'
order by discount_rate desc
limit 5;

-- 7. segment customers into new, returning, and loyal based on their total
-- number of previous purchases, and show the count of each segment ? 

with customer_type as (
select 'ï»¿Customer ID', 'Previous Purchases',
CASE
WHEN 'Previous Purchases' = 1 THEN 'New'
WHEN 'Previous Purchases' BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
from customer_shopping_behavior
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- 8. What are the top 3 most purchased products within category ?

with item_count as (
select 'Category',
'Item Purchased',
COUNT('ï»¿Customer ID') as total_orders,
ROW_NUMBER() over (partition by 'Category' order by 
count('ï»¿Customer ID') DESC ) as item_rank
from customer_shopping_behavior
group by 'Category', 'Item Purchased'
)
select item_rank, 'Category','Item Purchased', total_orders 
from item_count
where item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

SELECT `Subscription Status`,
       COUNT('ï»¿Customer ID') AS repeat_buyers
FROM customer_shopping_behavior
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;

-- 10. What is the revenue contribution of each age ?

SELECT 'Age',
       SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer_shopping_behavior
GROUP BY 'Age'
ORDER BY total_revenue DESC;





